services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./src/database.sqlite:/app/src/database.sqlite
      - ./logs:/app/logs
    env_file:
      - .env.prod
    environment:
      - PORT=${PORT:-8000}

volumes:
  db_data: